export const INIT_CART = "INIT_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_ONE_FROM_CART = "REMOVE_ONE_FROM_CART";
export const REMOVE_ALL_FROM_CART = "REMOVE_ALL_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";

export const INIT_PRODUCTS = "INIT_PRODUCTS";

export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';
export const FILTER_PRODUCT = 'FILTER_PRODUCT';